name: privacyblur
description: An app to pixelate portions of an image

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+31

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  shared_preferences: ^2.0.5
  flutter_translate: ^3.0.1
  flutter_styled_toast: ^2.0.0
  image_size_getter: ^1.0.0
  flutter_exif_rotation: ^0.4.1
  url_launcher: ^6.0.3
  package_info: ^2.0.0
  image_picker: ^0.7.5+2
  image: ^3.0.2
  image_gallery_saver: ^1.6.9
  permission_handler: ^7.2.0
  path_provider: ^2.0.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_translate_gen: ^2.0.0
  build_runner: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mockito: ^5.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # generate: true
  uses-material-design: true
  assets:
    - lib/resources/images/
    - lib/resources/i18n/
    - pubspec.yaml
      
  fonts:
    - family: PrivacyBlur
      fonts:
        - asset: lib/resources/fonts/PrivacyBlur.ttf
